// Generated by tools/gen_robot.py from mycobot_description/config/mycobot_280_arduino/{joint_limits,servos}.yaml. Do not edit.
#pragma once
#include <stdint.h>

namespace robot {
const int N_JOINTS = 6;
const float LIMIT_DEG[N_JOINTS] = {165, 140, 150, 150, 160, 180};   // model joint limits (±°)
const float VMAX_DPS = 90;   // speed limit (°/s)
const float AMAX_DPS2[N_JOINTS] = {400, 400, 400, 2000, 2000, 2000};   // acceleration limits (°/s²)
const int8_t JOINT_SIGN[N_JOINTS] = {-1, -1, 1, -1, -1, -1};   // angle = sign × (step − 2048) × 360 / 4096
const uint8_t GAINS[N_JOINTS][3] = {{32, 4, 16}, {32, 4, 16}, {32, 4, 16}, {32, 8, 0}, {32, 8, 0}, {32, 8, 0}};   // P, D, I (registers 21, 22, 23)
}  // namespace robot
