name = "MyCobot"
uuid = "d5306646-067b-4694-abf2-bb446ebd4c06"
authors = ["Henrique Ferrolho <henrique.ferrolho@gmail.com>"]
version = "0.1.0"

[deps]
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"

[compat]
LibSerialPort = "0.5"
