name = "MyCobot"
uuid = "d5306646-067b-4694-abf2-bb446ebd4c06"
authors = ["Henrique Ferrolho <henrique.ferrolho@gmail.com>"]
version = "0.1.0"

[deps]
LibSerialPort = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
MeshCatMechanisms = "6ad125db-dd91-5488-b820-c1df6aab299d"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"

[compat]
LibSerialPort = "0.5"
MeshCat = "1"
MeshCatMechanisms = "0.10"
RigidBodyDynamics = "2"
