// Forward kinematics of the arm for the Control page: the TCP position in the gamepad tab, and the tool
// orientation for "point the tool down" (Y). The end-effector controller runs on the ATOM (firmware 5.1,
// twist.h). Pure code, no DOM and no imports, so that scripts/test-kinematics.mjs runs it in Node.
//
// The chain comes from the URDF that the page loads (website/public/robot/, generated by tools/gen_robot.py
// from the one robot description). The test compares it with src/kinematics.jl (the poses in
// tools/firmware-tests/fk_reference.h, which the firmware's FK test uses too).
//
// Units: mm and rad inside; joint angles in degrees at the interface (as the ATOM).

export type Vec3 = [number, number, number];
export type Mat3 = number[]; // 3×3, row-major
export interface Pose {
  R: Mat3; // tool axes in the base frame (columns)
  p: Vec3; // mm, base frame
}

// --- Small vector algebra --------------------------------------------------------------------------

const D2R = Math.PI / 180;
export const I3 = (): Mat3 => [1, 0, 0, 0, 1, 0, 0, 0, 1];
export const mul3 = (a: Mat3, b: Mat3): Mat3 => {
  const c = new Array(9).fill(0);
  for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) for (let k = 0; k < 3; k++) c[3 * i + j] += a[3 * i + k] * b[3 * k + j];
  return c;
};
export const mulv = (a: Mat3, v: readonly number[]): Vec3 => [
  a[0] * v[0] + a[1] * v[1] + a[2] * v[2],
  a[3] * v[0] + a[4] * v[1] + a[5] * v[2],
  a[6] * v[0] + a[7] * v[1] + a[8] * v[2],
];
export const transpose = (a: Mat3): Mat3 => [a[0], a[3], a[6], a[1], a[4], a[7], a[2], a[5], a[8]];
const add = (a: readonly number[], b: readonly number[]): Vec3 => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
const scale = (a: readonly number[], s: number): Vec3 => [a[0] * s, a[1] * s, a[2] * s];
export const norm = (a: readonly number[]) => Math.hypot(...a);

/** Rotation by angle |w| about the axis w (rad), Rodrigues. */
export function expSO3(w: readonly number[]): Mat3 {
  const th = norm(w);
  if (th < 1e-12) return I3();
  const [x, y, z] = scale(w, 1 / th);
  const s = Math.sin(th), c = Math.cos(th), t = 1 - c;
  return [c + x * x * t, x * y * t - z * s, x * z * t + y * s, y * x * t + z * s, c + y * y * t, y * z * t - x * s, z * x * t - y * s, z * y * t + x * s, c + z * z * t];
}

/** Rotation vector (axis × angle, rad) of R. Exact for angles below π. */
export function logSO3(R: Mat3): Vec3 {
  const c = Math.max(-1, Math.min(1, (R[0] + R[4] + R[8] - 1) / 2));
  const th = Math.acos(c);
  const v: Vec3 = [R[7] - R[5], R[2] - R[6], R[3] - R[1]];
  if (th < 1e-6) return scale(v, 0.5);
  if (Math.PI - th < 1e-6) {
    // Near π: the axis from the diagonal.
    const k = [R[0], R[4], R[8]].indexOf(Math.max(R[0], R[4], R[8]));
    const a = [0, 0, 0];
    a[k] = Math.sqrt(Math.max(0, (R[4 * k] + 1) / 2));
    for (let i = 0; i < 3; i++) if (i !== k) a[i] = R[3 * i + k] / (2 * a[k]);
    return scale(a, th);
  }
  return scale(v, th / (2 * Math.sin(th)));
}

function rpy(r: number, p: number, y: number): Mat3 {
  const Rx: Mat3 = [1, 0, 0, 0, Math.cos(r), -Math.sin(r), 0, Math.sin(r), Math.cos(r)];
  const Ry: Mat3 = [Math.cos(p), 0, Math.sin(p), 0, 1, 0, -Math.sin(p), 0, Math.cos(p)];
  const Rz: Mat3 = [Math.cos(y), -Math.sin(y), 0, Math.sin(y), Math.cos(y), 0, 0, 0, 1];
  return mul3(Rz, mul3(Ry, Rx)); // URDF: fixed axes x, then y, then z
}

// --- The kinematic chain ---------------------------------------------------------------------------

interface Link {
  R: Mat3; // joint origin, in the parent link frame
  p: Vec3; // mm
  axis: Vec3 | null; // revolute axis in the joint frame; null = fixed
}

export class Chain {
  readonly links: Link[];
  constructor(links: Link[]) {
    this.links = links;
  }
  get dof() {
    return this.links.filter((l) => l.axis).length;
  }

  /** Pose of the tip link for joint angles in degrees, and the axis and origin of each joint (base frame). */
  fk(qDeg: readonly number[]): { pose: Pose; axes: Vec3[]; origins: Vec3[] } {
    let R = I3();
    let p: Vec3 = [0, 0, 0];
    const axes: Vec3[] = [];
    const origins: Vec3[] = [];
    let j = 0;
    for (const l of this.links) {
      p = add(p, mulv(R, l.p));
      R = mul3(R, l.R);
      if (l.axis) {
        const a = mulv(R, l.axis);
        axes.push(a);
        origins.push(p);
        R = mul3(R, expSO3(scale(l.axis, qDeg[j++] * D2R)));
      }
    }
    return { pose: { R, p }, axes, origins };
  }
}

/** The serial chain from the URDF root to `tip` (default: the flange of the arm, as src/kinematics.jl). */
export function parseChain(urdf: string, tip = 'joint6_flange'): Chain {
  const attr = (s: string, tag: string, name: string) => s.match(new RegExp(`<${tag}\\b[^>]*\\b${name}="([^"]*)"`))?.[1];
  const nums = (s: string | undefined) => (s ?? '0 0 0').trim().split(/\s+/).map(Number) as Vec3;
  const byChild = new Map<string, string>();
  for (const m of urdf.matchAll(/<joint\b[\s\S]*?<\/joint>/g)) {
    const child = attr(m[0], 'child', 'link');
    if (child) byChild.set(child, m[0]);
  }
  const links: Link[] = [];
  for (let name = tip, j = byChild.get(name); j; j = byChild.get(name)) {
    const type = attr(j, 'joint', 'type');
    if (type !== 'fixed' && type !== 'revolute') throw new Error(`URDF joint type ${type} is not supported`);
    const [r, pp, y] = nums(attr(j, 'origin', 'rpy'));
    links.unshift({ R: rpy(r, pp, y), p: scale(nums(attr(j, 'origin', 'xyz')), 1000), axis: type === 'revolute' ? nums(attr(j, 'axis', 'xyz') ?? '1 0 0') : null });
    name = attr(j, 'parent', 'link')!;
  }
  if (!links.length) throw new Error(`URDF: no chain to ${tip}`);
  return new Chain(links);
}

/** Pose of the TCP (`tcp`: in the flange frame, mm) for joint angles (°). */
export function tcpPose(chain: Chain, qDeg: readonly number[], tcp: readonly number[]): Pose {
  const { pose } = chain.fk(qDeg);
  return { R: pose.R, p: add(pose.p, mulv(pose.R, tcp)) };
}
