// Generated by tools/gen_robot.py from mycobot_description/config/mycobot_280_arduino/{joint_limits,servos}.yaml. Do not edit.
// J1-J6, then J7 (the adaptive gripper, when the ATOM finds it).
export const N_ARM = 6;
export const SIGN = [-1, -1, 1, -1, -1, -1, 1] as const; // angle = sign × (step − 2048) × 360 / 4096
export const STEPS_PER_DEG = 4096 / 360;
export const LIMIT_MIN = [-165, -140, -150, -150, -160, -225, -51.5039] as const; // joint limits (°); J7: the end stops
export const LIMIT_MAX = [165, 140, 150, 150, 160, 135, 0] as const;
export const VMAX = 90; // speed limit (°/s)
export const AMAX = [400, 400, 400, 2000, 2000, 2000, 2000] as const; // acceleration limits (°/s²)
