// Generated by tools/gen_robot.py from mycobot_description/config/mycobot_280_arduino/{joint_limits,servos}.yaml. Do not edit.
export const SIGN = [-1, -1, 1, -1, -1, -1] as const; // angle = sign × (step − 2048) × 360 / 4096
export const STEPS_PER_DEG = 4096 / 360;
export const LIMITS = [165, 140, 150, 150, 160, 180] as const; // model joint limits (±°)
export const VMAX = 90; // speed limit (°/s)
export const AMAX = [400, 400, 400, 2000, 2000, 2000] as const; // acceleration limits (°/s²)
