# Flange poses from src/kinematics.jl (RigidBodyDynamics.jl) for the firmware's FK test (test_twist_check.cpp).
# Run it again when the URDF changes:  julia --project=. tools/firmware-tests/fk_reference.jl
using MyCobot
import RigidBodyDynamics as RBD
const S = RBD.MechanismState(MyCobot.load_mechanism())
const QS = [[0, 0, 0, 0, 0, 0], [10, -20, 30, -40, 50, -60], [-77, -27, 36, 23, 75, -56], [65, 68, 41, -80, 17, -11], [0, 0, -90, 0, 0, 0]]
f(x) = string(round(x; digits=7), "f")
open(joinpath(@__DIR__, "fk_reference.h"), "w") do io
    println(io, "// Generated by tools/firmware-tests/fk_reference.jl from src/kinematics.jl. Do not edit.")
    println(io, "// Joint angles (°), flange position (mm) and rotation (row-major) in the base frame.")
    println(io, "#pragma once\nconst int FK_REF_N = $(length(QS));\nconst float FK_REF_Q[][6] = {", join(["{" * join(f.(Float64.(q)), ", ") * "}" for q in QS], ", "), "};")
    T = [MyCobot.flange_transform(S, Float64.(q)) for q in QS]
    println(io, "const float FK_REF_P[][3] = {", join(["{" * join(f.(1000 .* Vector(RBD.translation(t))), ", ") * "}" for t in T], ", "), "};")
    println(io, "const float FK_REF_R[][9] = {", join(["{" * join(f.(vec(Matrix(RBD.rotation(t))')), ", ") * "}" for t in T], ", "), "};")
end
