# /// script
# requires-python = ">=3.10"
# dependencies = ["xacro==2.1.1", "pyyaml>=6"]
# ///
"""
Generate the robot description and the parameter tables from one source:
mycobot_description/urdf/mycobot_280_arduino/mycobot_280_arduino.urdf.xacro and
mycobot_description/config/mycobot_280_arduino/{joint_limits,servos,calibration}.yaml.

    uv run tools/gen_robot.py           # write the generated files
    uv run tools/gen_robot.py --check   # exit 1 if a generated file is not up to date

Writes:
    mycobot_description/urdf/mycobot_280_arduino/mycobot_280_arduino.urdf   Julia (RigidBodyDynamics.jl)
    website/public/robot/mycobot_280_arduino.urdf                           Control page (.glb meshes)
    firmware/atom_controller/robot_params.h                                 controller firmware
    website/src/control/robot_params.ts                                     Control page
    tools/robot_params.py                                                   simulator (tools/atom_sim.py)
    src/robot_params.jl                                                     Julia package
"""
import math
import os
import sys

import xacro
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESC = os.path.join(ROOT, "mycobot_description")
XACRO = os.path.join(DESC, "urdf", "mycobot_280_arduino", "mycobot_280_arduino.urdf.xacro")
CONFIG = os.path.join(DESC, "config", "mycobot_280_arduino")
SOURCES = "mycobot_description/config/mycobot_280_arduino/{joint_limits,servos}.yaml"
CALIBRATION = "mycobot_description/config/mycobot_280_arduino/calibration.yaml"


def num(x):
    """A short decimal for code: 165.0 -> 165, 0.82 -> 0.82."""
    r = round(x, 6)
    return str(int(r)) if r == int(r) else repr(r)


def urdf(mesh_uri, mesh_ext):
    doc = xacro.process_file(XACRO, mappings={"mesh_uri": mesh_uri, "mesh_ext": mesh_ext})
    return doc.toprettyxml(indent="  ")


def params():
    limits = yaml.safe_load(open(os.path.join(CONFIG, "joint_limits.yaml")))["joint_limits"]
    servos = yaml.safe_load(open(os.path.join(CONFIG, "servos.yaml")))
    names = list(servos["joints"])
    if names != list(limits):
        sys.exit("joint_limits.yaml and servos.yaml list different joints")
    s = [servos["joints"][n] for n in names]
    limit_deg = [math.degrees(limits[n]["max_position"]) for n in names]
    if any(abs(math.degrees(limits[n]["min_position"]) + d) > 1e-4 for n, d in zip(names, limit_deg)):
        sys.exit("the firmware and the Control page need symmetric position limits")
    vmax = {round(math.degrees(limits[n]["max_velocity"]), 4) for n in names}
    if len(vmax) != 1:
        sys.exit("the firmware has one speed limit for all joints: give every joint the same max_velocity")
    steps_per_deg = servos["steps_per_turn"] / 360
    calib_path = os.path.join(ROOT, CALIBRATION)
    calib = yaml.safe_load(open(calib_path)) if os.path.exists(calib_path) else {}
    corr = (calib or {}).get("encoder_correction") or {}
    if set(corr) - set(names):
        sys.exit(f"calibration.yaml: unknown joints {sorted(set(corr) - set(names))}")
    n_terms = max([len(c[k]) for c in corr.values() for k in ("sin", "cos")] + [0])
    pad = lambda xs: [float(x) for x in xs] + [0.0] * (n_terms - len(xs))
    return {
        "encoder_correction": [(pad(corr.get(n, {}).get("sin", [])), pad(corr.get(n, {}).get("cos", []))) for n in names],
        "names": names,
        "limit_deg": [round(d, 4) for d in limit_deg],
        "vmax_dps": vmax.pop(),
        "amax_dps2": [round(math.degrees(limits[n]["max_acceleration"]), 4) for n in names],
        "ids": [x["id"] for x in s],
        "sign": [x["sign"] for x in s],
        "gains": [x["gains"] for x in s],
        "servo_amax_dps2": [x["max_acceleration_register"] * 100 / steps_per_deg for x in s],
        "wn": [x["wn"] for x in s],
        "zeta": [x["zeta"] for x in s],
        "center": servos["center_step"],
        "steps_per_turn": servos["steps_per_turn"],
    }


def header(comment, sources=SOURCES):
    return f"{comment} Generated by tools/gen_robot.py from {sources}. Do not edit.\n"


def c_params(p):
    arr = lambda xs: "{" + ", ".join(num(x) for x in xs) + "}"
    return (header("//") + "#pragma once\n#include <stdint.h>\n\nnamespace robot {\n"
            f"const int N_JOINTS = {len(p['names'])};\n"
            f"const float LIMIT_DEG[N_JOINTS] = {arr(p['limit_deg'])};   // model joint limits (±°)\n"
            f"const float VMAX_DPS = {num(p['vmax_dps'])};   // speed limit (°/s)\n"
            f"const float AMAX_DPS2[N_JOINTS] = {arr(p['amax_dps2'])};   // acceleration limits (°/s²)\n"
            f"const int8_t JOINT_SIGN[N_JOINTS] = {arr(p['sign'])};   // angle = sign × (step − {p['center']}) × 360 / {p['steps_per_turn']}\n"
            f"const uint8_t GAINS[N_JOINTS][3] = {{{', '.join(arr(g) for g in p['gains'])}}};   // P, D, I (registers 21, 22, 23)\n"
            "}  // namespace robot\n")


def ts_params(p):
    arr = lambda xs: "[" + ", ".join(num(x) for x in xs) + "]"
    return (header("//") +
            f"export const SIGN = {arr(p['sign'])} as const; // angle = sign × (step − {p['center']}) × 360 / {p['steps_per_turn']}\n"
            f"export const STEPS_PER_DEG = {p['steps_per_turn']} / 360;\n"
            f"export const LIMITS = {arr(p['limit_deg'])} as const; // model joint limits (±°)\n"
            f"export const VMAX = {num(p['vmax_dps'])}; // speed limit (°/s)\n"
            f"export const AMAX = {arr(p['amax_dps2'])} as const; // acceleration limits (°/s²)\n")


def py_params(p):
    tup = lambda xs: "(" + ", ".join(num(x) for x in xs) + ")"
    return (header("#") +
            f"SIGN = {tup(p['sign'])}   # angle = sign × (step − {p['center']}) × 360 / {p['steps_per_turn']}\n"
            f"STEPS_PER_DEG = {p['steps_per_turn']} / 360\n"
            f"LIMITS = {tup(p['limit_deg'])}   # model joint limits (±°)\n"
            f"VMAX = {num(p['vmax_dps'])}   # speed limit (°/s)\n"
            f"AMAX = {tup(p['amax_dps2'])}   # acceleration limits (°/s²)\n")


def jl_correction(p):
    tup = lambda xs: "(" + ", ".join(num(x) + (".0" if num(x).lstrip("-").isdigit() else "") for x in xs) + ("," if len(xs) == 1 else "") + ")"
    rows = ",\n".join(f"    (sin = {tup(s)}, cos = {tup(c)})" for s, c in p["encoder_correction"])
    return ("\n\"\"\"Encoder correction of each joint for this robot (degrees; from " + CALIBRATION + "):\n"
            "true angle = encoder angle − Σ sin[k]·sin(k·q) − Σ cos[k]·(cos(k·q) − 1). See `encoder_error`.\"\"\"\n"
            f"const ENCODER_CORRECTION = (\n{rows},\n)\n")


def jl_params(p):
    jf = lambda x: (num(x) + ".0") if num(x).lstrip("-").isdigit() else num(x)   # a Julia Float64
    vec = lambda xs: "[" + ", ".join(jf(x) if isinstance(x, float) else str(x) for x in xs) + "]"
    return (header("#", SOURCES.replace("servos}", "servos,calibration}")) + "\n"
            f"\"Bus ID of each joint servo.\"\nconst SERVO_IDS = UInt8.({vec(p['ids'])})\n\n"
            f"\"Joint angle direction against the servo position: angle = sign × (step − {p['center']}) / STEPS_PER_DEG.\"\n"
            f"const JOINT_SIGN = ({', '.join(f'{s:+d}' for s in p['sign'])})\n\n"
            f"const STEPS_PER_DEG = {p['steps_per_turn']} / 360\n\n"
            f"\"Acceleration limits of the controller firmware (°/s²), below the servo limits `SERVO_AMAX`.\"\n"
            f"const FIRMWARE_AMAX = {vec([float(x) for x in p['amax_dps2']])}\n\n"
            f"\"Speed limit of the controller firmware (°/s).\"\nconst FIRMWARE_VMAX = {jf(float(p['vmax_dps']))}\n\n"
            f"\"Position-loop gains (P, D, I) that the controller firmware writes at power-up.\"\n"
            f"const GAINS = [{', '.join('(' + ', '.join(str(x) for x in g) + ')' for g in p['gains'])}]\n\n"
            f"\"Natural frequency ωn (rad/s) of each joint servo, from acceleration-limited chirps.\"\n"
            f"const SERVO_WN = {vec([float(x) for x in p['wn']])}\n\n"
            f"\"Damping ratio ζ of each joint servo.\"\nconst SERVO_ZETA = {vec([float(x) for x in p['zeta']])}\n\n"
            f"\"Acceleration limit of each servo (°/s²): factory register 85 × 100 steps/s².\"\n"
            f"const SERVO_AMAX = {vec([float(x) for x in p['servo_amax_dps2']])}\n" + jl_correction(p))


def outputs():
    p = params()
    return {
        "mycobot_description/urdf/mycobot_280_arduino/mycobot_280_arduino.urdf":
            urdf("package://mycobot_description/urdf/mycobot_280_arduino/", "dae"),
        "website/public/robot/mycobot_280_arduino.urdf": urdf("", "glb"),
        "firmware/atom_controller/robot_params.h": c_params(p),
        "website/src/control/robot_params.ts": ts_params(p),
        "tools/robot_params.py": py_params(p),
        "src/robot_params.jl": jl_params(p),
    }


def main():
    check = "--check" in sys.argv[1:]
    stale = []
    for rel, text in outputs().items():
        path = os.path.join(ROOT, rel)
        old = open(path).read() if os.path.exists(path) else None
        if old == text:
            continue
        if check:
            stale.append(rel)
        else:
            open(path, "w").write(text)
            print(f"wrote {rel}")
    if stale:
        print("not up to date (run: uv run tools/gen_robot.py):\n  " + "\n  ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
