# Generated by tools/gen_robot.py from mycobot_description/config/mycobot_280_arduino/{joint_limits,servos}.yaml. Do not edit.
# J1-J6, then J7 (the adaptive gripper, when the ATOM finds it).
N_ARM = 6
SIGN = (-1, -1, 1, -1, -1, -1, 1)   # angle = sign × (step − 2048) × 360 / 4096
STEPS_PER_DEG = 4096 / 360
LIMIT_MIN = (-165, -140, -150, -150, -160, -225, -51.5039)   # joint limits (°); J7: the end stops
LIMIT_MAX = (165, 140, 150, 150, 160, 135, 0)
MULTI_TURN = (False, False, False, False, False, True, False)   # servo reads and moves past one turn
VMAX = 90   # speed limit (°/s)
AMAX = (400, 400, 400, 2000, 2000, 2000, 2000)   # acceleration limits (°/s²)
GRIPPER_TCP_MM = (-0.6, 8.2, 100)   # the TCP with the gripper, flange frame (mm)
