# Generated by tools/gen_robot.py from mycobot_description/config/mycobot_280_arduino/{joint_limits,servos}.yaml. Do not edit.
SIGN = (-1, -1, 1, -1, -1, -1)   # angle = sign × (step − 2048) × 360 / 4096
STEPS_PER_DEG = 4096 / 360
LIMITS = (165, 140, 150, 150, 160, 180)   # model joint limits (±°)
VMAX = 90   # speed limit (°/s)
AMAX = (400, 400, 400, 2000, 2000, 2000)   # acceleration limits (°/s²)
