# Generated by tools/gen_robot.py from mycobot_description/config/mycobot_280_arduino/{joint_limits,servos}.yaml. Do not edit.
SIGN = (-1, -1, 1, -1, -1, -1)   # angle = sign × (step − 2048) × 360 / 4096
STEPS_PER_DEG = 4096 / 360
LIMIT_MIN = (-165, -140, -150, -150, -160, -220)   # model joint limits (°)
LIMIT_MAX = (165, 140, 150, 150, 160, 135)
MULTI_TURN = (False, False, False, False, False, True)   # servo reads and moves past one turn
VMAX = 90   # speed limit (°/s)
AMAX = (400, 400, 400, 2000, 2000, 2000)   # acceleration limits (°/s²)
