# Generated by tools/gen_robot.py from mycobot_description/config/mycobot_280_arduino/{joint_limits,servos,calibration}.yaml. Do not edit.

"Bus ID of each joint servo."
const SERVO_IDS = UInt8.([1, 2, 3, 4, 5, 6])

"Joint angle direction against the servo position: angle = sign × (step − 2048) / STEPS_PER_DEG."
const JOINT_SIGN = (-1, -1, +1, -1, -1, -1)

const STEPS_PER_DEG = 4096 / 360

"Acceleration limits of the controller firmware (°/s²), below the servo limits `SERVO_AMAX`."
const FIRMWARE_AMAX = [400.0, 400.0, 400.0, 2000.0, 2000.0, 2000.0]

"Speed limit of the controller firmware (°/s)."
const FIRMWARE_VMAX = 90.0

"Position-loop gains (P, D, I) that the controller firmware writes at power-up."
const GAINS = [(32, 4, 16), (32, 4, 16), (32, 4, 16), (32, 8, 0), (32, 8, 0), (32, 8, 0)]

"Natural frequency ωn (rad/s) of each joint servo, from acceleration-limited chirps."
const SERVO_WN = [14.8, 14.7, 14.2, 34.4, 52.4, 54.9]

"Damping ratio ζ of each joint servo."
const SERVO_ZETA = [0.82, 0.75, 0.78, 0.65, 0.77, 0.83]

"Acceleration limit of each servo (°/s²): factory register 85 × 100 steps/s²."
const SERVO_AMAX = [439.453125, 439.453125, 439.453125, 2197.265625, 2197.265625, 2197.265625]

"""Encoder correction of each joint for this robot (degrees; from mycobot_description/config/mycobot_280_arduino/calibration.yaml):
true angle = encoder angle − Σ sin[k]·sin(k·q) − Σ cos[k]·(cos(k·q) − 1). See `encoder_error`."""
const ENCODER_CORRECTION = (
    (sin = (0.0, 0.0), cos = (0.0, 0.0)),
    (sin = (0.0, 0.0), cos = (0.0, 0.0)),
    (sin = (0.0, 0.0), cos = (0.0, 0.0)),
    (sin = (0.0, 0.0), cos = (0.0, 0.0)),
    (sin = (1.493, 0.598), cos = (0.018, -0.377)),
    (sin = (0.0, 0.0), cos = (0.0, 0.0)),
)
